-- AlterTable RunVariant: validation / A-B fields (worker run-variants + API /variants)
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "config" JSONB;
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "accuracy" DOUBLE PRECISION;
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "pnl" DOUBLE PRECISION;
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "baselineBuy" DOUBLE PRECISION;
ALTER TABLE "RunVariant" ADD COLUMN IF NOT EXISTS "baselineSell" DOUBLE PRECISION;
