-- AlterTable
ALTER TABLE "AgentInfoState" ADD COLUMN     "confidence" DOUBLE PRECISION,
ADD COLUMN     "herding" DOUBLE PRECISION,
ADD COLUMN     "riskTolerance" DOUBLE PRECISION,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
